# Generated by Django 2.1.2 on 2018-11-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('Order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=50)),
                ('total', models.DecimalField(decimal_places=2, max_digits=3)),
                ('number', models.IntegerField()),
                ('confirmed', models.BooleanField(default=False)),
            ],
        ),
    ]
